### ISSUE TITLE
About the forcast result in the dataset

### ISSUE THREAD

**Issue by rs-lsl** [google-research/weatherbench2#104]
Very appreciate for the released code and dataset, however, i found that the released forcast results from the era5 forcast, pangu, keisler etc. have no total_precipitation_6hr results. Does the original author have not released the results, or, you will release the total_precipitation_6hr results in the future, very looking forward to it!

**Comment by shoyer** [comment]
The Pangu and Keisler models (as well as many others) do not predict precipitation. The main issue is that the training data for precipitation in ERA5 is very low quality.

**Comment by rs-lsl** [comment]
Thank you, does the 'low quality' means the inaccuracy? I notice that the forcastnet and fuxi have predicted the precipitation in 6 hour and achieve the great performance. And if there are some methods to improve its quality, very thanks.

**Comment by shoyer** [comment]
Correct, ERA5 is generally considered to be a low quality source of ground truth data for precipitation because it is only based on ECMWF's model, not any direct observations. It is also relatively easy to obtain low RMSE for precipitation by making blurry predictions that are not physically consistent.

**Comment by rs-lsl** [comment]
Very thanks^_^
